### ISSUE TITLE
Undefined variables for compute_itm_hardneg

### ISSUE THREAD

**Issue by AdityaAgrawal-code** [microsoft/FIBER#11]
Please check this line: https://github.com/microsoft/FIBER/blob/92c62049913e1a8da1cb8270cd9b6138110e7aa6/coarse_grained/fiber/modules/fiber_module.py#L448

Where is image_neg, text_neg, text_mask_neg being defined (to be passed into compute_itm_hardneg)?

I suspect this a bug. As per my understanding these values are being returned by compute_itc in the previous if block and must be stored to be passed again in itm.

Please have a look and let me know!

**Comment by zdou0830** [comment]
Hi, thanks! it should be fixed now.

**Comment by AdityaAgrawal-code** [comment]
Thank you!
