### ISSUE TITLE
where to download the pre-trained model weight? 

### ISSUE THREAD

**Issue by XiaokunFeng** [microsoft/FIBER#16]
Hi, thanks for your great work!
Where can I download model pre training weights？I don't see the link in the readme file.

**Comment by zdou0830** [comment]
You can find the links in https://github.com/microsoft/FIBER/tree/main/coarse_grained and https://github.com/microsoft/FIBER/tree/main/fine_grained

**Comment by XiaokunFeng** [comment]
OK, thanks !!!

**Comment by aRthur08701244** [comment]
@XiaokunFeng @zdou0830 
Hi, as you can see many people proposed the issue that the pretraining weights disappeared (#22 #21 ). I'm wondering if you guys can provide it if you already saved it. Thank you!
