### ISSUE TITLE
Question of Classification Result 

### ISSUE THREAD

**Issue by chaos1992** [microsoft/FIBER#8]
Thanks for your great work! How can I reproduce the result of Table 18 in the paper?

Looking forward to your reply!

**Comment by zdou0830** [comment]
Hello, you can use the Swin Transformer code (https://github.com/microsoft/Swin-Transformer) with our pretrained weights.

**Comment by chaos1992** [comment]
@zdou0830 Sorry for another question. What is the language input of Fig. 3(c) when I infer FIBER? I mean, does FIBER need to have language input when we're doing an image caption task?

**Comment by zdou0830** [comment]
For image captioning, FIBER generates tokens autoregressively as in standard seq2seq models.

**Comment by chaos1992** [comment]
> 

Got it, thanks
